name: "Deploy Sphinx"
 
# execute this workflow automatically when a we push to master
on: 
  push:
    branches: ['main']
    paths: ['docs/**']

permissions:
 contents: write
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build html
        uses: ammaraskar/sphinx-action@master
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
         name: html-docs
         path: docs/_build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: docs/_build/html